#!/bin/bash

thumbgeom="240x240"
thumbext="jpg"
thumbdir="tn"
script=$(basename $0)

main () {
cwd=$(pwd)
find . -type d \( -path '*/\.*' -o -path '*/tn' \) -prune -o -type d -print | sed -e 's/.//' -e 's/\///' | sort | while IFS= read -r cdir
  do
    cd "${cdir}"
    title=$(awk -F / '{print $NF}' <<< ${cdir})
    css=$(sed -e 's/\/[^\/]*/\/../g' -e 's/.\///' <<< ${cdir})
    depth=$(awk -F / '{print NF}' <<< ${cdir})
    dots=$(printf "%0.s../" $(seq $depth))
    files=$(find . -maxdepth 1 -type f ! -name ".*" ! -name index.html ! -name ${script} ! -name README.md)
    echo "Indexing $(pwd)"
    header
    images
    directories
    footer
    cd "$cwd"
done
}

header () {
    echo '<!DOCTYPE html>' > index.html
    echo '<html lang="en">' >> index.html
    echo '  <head>' >> index.html
    echo "    <title>pics from ${title}</title>" >> index.html
    echo '    <meta charset="utf-8" />' >> index.html
    echo '    <meta name="viewport" content="width=device-width, initial-scale=1.0">' >> index.html
    if [[ $depth = 0 ]]
      then  
        echo "    <link href=\".css/main.css\" rel=\"stylesheet\" type=\"text/css\" />" >> index.html
        echo "    <link href=\".css/popup.css\" rel=\"stylesheet\" type=\"text/css\" />" >> index.html
        echo "    <script type=\"text/javascript\" src=\".js/jquery-1.11.0.min.js\"></script>" >> index.html
        echo "    <script type=\"text/javascript\" src=\".js/popup.min.js\"></script>" >> index.html
      else
        echo "    <link href=\"${dots}.css/main.css\" rel=\"stylesheet\" type=\"text/css\" />" >> index.html
        echo "    <link href=\"${dots}.css/popup.css\" rel=\"stylesheet\" type=\"text/css\" />" >> index.html
        echo "    <script src=\"${dots}.js/jquery-1.11.0.min.js\"></script>" >> index.html
        echo "    <script src=\"${dots}.js/popup.min.js\"></script>" >> index.html
    fi
    echo '  </head>' >> index.html
    echo '  <body>' >> index.html
    echo '    <div id="page">' >> index.html
    echo '    <header>' >> index.html
    breadcrumbs
    echo '    </header>' >> index.html
    echo '    <div id="content">' >> index.html
}

breadcrumbs () {
    if [[ $depth != 0 ]]
      then
        echo '      <ul class="breadcrumb">' >> index.html
        echo "        <li class=\"crumb\">// </li>" >> index.html
    until [ $depth = 0 ]
      do
        local dots=$(printf "%0.s../" $(seq $depth))
        pushd $dots > /dev/null 2>&1
        here=$(awk -F/ '{ print $NF }' <<< $PWD)
        popd > /dev/null 2>&1
        echo "        <li class=\"crumb\"><a href=\"$dots\">${here}</a></li>" >> index.html
        echo "        <li class=\"crumb\">// </li>" >> index.html
        (( depth = $depth-1 ))
    done
        echo "        <li class=\"crumb title\">${title}</li>" >> index.html
        echo '      </ul>' >> index.html
    fi
}

directories () {
   find . -maxdepth 1 -type d ! -name ".*" ! -name "tn" | sed -e 's/.//' -e 's/\///' | sort -rh | while IFS= read -r dir
      do
	date=$(awk -F _ '{print $1}' <<< "${dir}")
	place=$(echo "${dir}" | awk -F _ '{print $2}' | sed 's/-/ /')
        echo '      <div class="list">' >> index.html
        echo "        <a href=\"${dir}\"><h2>${date}</h2>" >> index.html
        if [[ $place ]]
          then
            echo -n "        <h3>\"${place}\"</h3>" >> index.html
        fi
            echo "        </a>" >> index.html
        echo '        <ul>' >> index.html
        find "$dir" -mindepth 1 -maxdepth 1 -type d ! -name ".*" ! -name "tn" | sort -h | while IFS= read -r subdir
          do
            basedir=$(basename "${subdir}")
            echo "          <li><a href=\"${subdir}\">${basedir}</a></li>" >> index.html
        done
        echo '        </ul>' >> index.html
        echo '      </div>' >> index.html
    done
}

images () {
    if [[ $files ]]
      then
        echo '    <div class="thumb">' >> index.html
        for img in *
          do
            if [[ "$img" = *.jpg ]] || [[ "$img" = *.png ]] || [[ "$img" = *.gif ]]
              then
                tn=$(thumb -geom "$thumbgeom" -type "$thumbext" -dir "$thumbdir" -crop "$img")
                echo "      <a href=\"${img}\"><img src=\"${tn}\" alt=\"${img}\" /></a>" >> index.html
            fi
            if [[ "$img" = *.ogv ]]
              then
                ffmpeg -loglevel panic -n -i "$img" -ss 00:00:0.635 -f image2 -vframes 1 "${img}.jpg" < /dev/null 
                tn=$(thumb -geom "$thumbgeom" -type "$thumbext" -dir "$thumbdir" -crop "${img}.jpg")
                rm "${img}.jpg"
                echo '<!DOCTYPE html>' > "tn/${img}.html"
                echo '<html lang="en">' >> "tn/${img}.html"
                echo '  <head>' >> "tn/${img}.html"
                echo "    <title>pics from ${title}</title>" >> "tn/${img}.html"
                echo '    <meta charset="utf-8" />' >> "tn/${img}.html"
                echo '        <meta name="viewport" content="width=device-width, initial-scale=1.0">' >> "tn/${img}.html"
                echo "    <link href=\"../${dots}.css/main.css\" rel=\"stylesheet\" type=\"text/css\" />" >> "tn/${img}.html"
                echo '  </head>' >> "tn/${img}.html"
                echo '  <body>' >> "tn/${img}.html"
                echo '      <header>' >> "tn/${img}.html"
                echo '      </header>' >> "tn/${img}.html"
                echo '      <div class="full">' >> "tn/${img}.html"
                echo "        <a href=\"tn/${img}.html\" class=\"mfp-iframe\"><img src=\"${tn}\" alt=\"${img}\" /></a>" >> index.html
                echo "        <video src=\"../${img}\" controls>Your browser does not support the video tag</video>" >> "tn/${img}.html"
                echo '      </div>' >> "tn/${img}.html"
                echo '  </body>' >> "tn/${img}.html"
                echo '</html>' >> "tn/${img}.html"
            fi
            if [[ "$img" = *.ogg ]]
              then
                echo "        <audio src=\"${img}\" controls>Your browser does not support the audio tag</audio>" >> index.html
            fi
        done
        echo '    </div>' >> index.html
        echo '    <script type="text/javascript">' >> index.html
        echo '      $(document).ready(function() {' >> index.html
        echo "        \$('.thumb').magnificPopup({" >> index.html
        echo "          delegate: 'a'," >> index.html
        echo "          type: 'image'," >> index.html
        echo "          disableOn: 767," >> index.html
        echo '          gallery: {' >> index.html
        echo '            enabled: true,' >> index.html
        echo '          },' >> index.html
	echo "		callbacks: {" >> index.html
	echo "		  buildControls: function() {" >> index.html
	echo "		    // re-appends controls inside the main container" >> index.html
	echo "		    this.contentContainer.append(this.arrowLeft.add(this.arrowRight));" >> index.html
	echo "		  }" >> index.html
	echo "		}" >> index.html
        echo '        });' >> index.html
        echo '      });' >> index.html
        echo '    </script>' >> index.html
        fi
}

footer () {
    depth=$(awk -F / '{print NF}' <<< ${cdir})
    echo '    </div>' >> index.html
    echo '    <footer>' >> index.html
    breadcrumbs
    echo '    </footer>' >> index.html
    echo '    </div>' >> index.html
    echo '  </body>' >> index.html
    echo '</html>' >> index.html
}

main
