#!/bin/bash

thumbgeom="240x240"
thumbdir="tn"
script=$(basename "$0")

main () {
cwd=$(pwd)
find . -type d \( -path '*/\.*' -o -path "*/${thumbdir}" \) -prune -o -type d -print | sed -e 's/.//' -e 's/\///' | sort | while IFS= read -r cdir
  do
    cd "${cdir}"
    title=$(awk -F / '{print $NF}' <<< "${cdir}")
    css=$(sed -e 's/\/[^\/]*/\/../g' -e 's/.\///' <<< "${cdir}")
    depth=$(awk -F / '{print NF}' <<< "${cdir}")
    dots=$(printf "%0.s../" $(seq $depth))
    files=$(find . -maxdepth 1 -type f ! -name ".*" ! -name index.html ! -name "${script}" ! -name README.md)
    subdirs=$(find . -mindepth 1 -maxdepth 1 -type d ! -name ".*" ! -name "${thumbdir}")
    echo "Indexing $(pwd)"
    header
    directories
    images $1
    footer
    cd "$cwd"
done
}

header () {
    echo '<!DOCTYPE html>' > index.html
    echo '<html lang="en">' >> index.html
    echo '  <head>' >> index.html
    echo "    <title>pics from ${title}</title>" >> index.html
    echo '    <meta charset="utf-8" />' >> index.html
    echo '    <meta name="viewport" content="width=device-width, initial-scale=1.0">' >> index.html
    if [[ $depth = 0 ]]
      then  
        echo "    <link href=\".css/main.css\" rel=\"stylesheet\" type=\"text/css\" />" >> index.html
      else
        echo "    <link href=\"${dots}.css/main.css\" rel=\"stylesheet\" type=\"text/css\" />" >> index.html
    fi
    echo '  </head>' >> index.html
    echo '  <body>' >> index.html
    echo '    <div id="page">' >> index.html
    echo '    <header>' >> index.html
    breadcrumbs
    echo '    </header>' >> index.html
    echo '    <div id="content">' >> index.html
}

breadcrumbs () {
    if [[ $depth != 0 ]]
      then
        echo '      <ul class="breadcrumb">' >> index.html
        echo "        <li class=\"crumb\">// </li>" >> index.html
    until [ $depth = 0 ]
      do
        local dots=$(printf "%0.s../" $(seq $depth))
        pushd $dots > /dev/null 2>&1
        here=$(awk -F/ '{ print $NF }' <<< $PWD)
        popd > /dev/null 2>&1
        echo "        <li class=\"crumb\"><a href=\"$dots\">${here}</a></li>" >> index.html
        echo "        <li class=\"crumb\">// </li>" >> index.html
        local depth=$(( $depth-1 ))
    done
        echo "        <li class=\"crumb title\">${title}</li>" >> index.html
        echo '      </ul>' >> index.html
    fi
}

directories () {
   if [[ $depth = 0 ]]
     then  
       find . -maxdepth 1 -type d ! -name ".*" ! -name "${thumbdir}" | sed -e 's/.//' -e 's/\///' | sort -rh | while IFS= read -r dir
          do
            date=$(awk -F _ '{print $1}' <<< "${dir}")
            place=$(echo "${dir}" | awk -F _ '{print $2}' | sed 's/-/ /g')
            echo '      <div class="list">' >> index.html
            if [[ $place ]]
              then
                echo "        <a href=\"${dir}\"><h2>${date}</h2>" >> index.html
                echo "        <h3>\"${place}\"</h3></a>" >> index.html
    	  else
                echo "        <a href=\"${dir}\"><h2>${date}</h2></a>" >> index.html
            fi
    	if [[ $subdirs ]]
    	  then
              echo '        <ul>' >> index.html
              find "$dir" -mindepth 1 -maxdepth 1 -type d ! -name ".*" ! -name "${thumbdir}" | sort -h | while IFS= read -r subdir
                do
                  basedir=$(basename "${subdir}")
                  echo "          <li><a href=\"${subdir}\">${basedir}</a></li>" >> index.html
              done
              echo '        </ul>' >> index.html
    	fi
            echo '      </div>' >> index.html
        done
     else
       find . -maxdepth 1 -type d ! -name ".*" ! -name "${thumbdir}" | sed -e 's/.//' -e 's/\///' | sort -h | while IFS= read -r dir
          do
            date=$(awk -F _ '{print $1}' <<< "${dir}")
            place=$(echo "${dir}" | awk -F _ '{print $2}' | sed 's/-/ /g')
            echo '      <div class="list">' >> index.html
            if [[ $place ]]
              then
                echo "        <a href=\"${dir}\"><h2>${date}</h2>" >> index.html
                echo "        <h3>\"${place}\"</h3></a>" >> index.html
          else
                echo "        <a href=\"${dir}\"><h2>${date}</h2></a>" >> index.html
            fi
            if [[ $subdirs ]]
              then
              echo '        <ul>' >> index.html
              find "$dir" -mindepth 1 -maxdepth 1 -type d ! -name ".*" ! -name "${thumbdir}" | sort -h | while IFS= read -r subdir
                do
                  basedir=$(basename "${subdir}")
                  echo "          <li><a href=\"${subdir}\">${basedir}</a></li>" >> index.html
              done
              echo '        </ul>' >> index.html
            fi
            echo '      </div>' >> index.html
        done
   fi
}

images () {
    if [[ $files ]]
      then
        if [ ! -d "${thumbdir}" ]
	  then
            mkdir "${thumbdir}"
        fi
        echo '      <div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls">' >> index.html
        echo '        <div class="slides"></div>' >> index.html
        echo '        <h3 class="title">Links</h3>' >> index.html
        echo '        <a class="prev">‹</a>' >> index.html
        echo '        <a class="next">›</a>' >> index.html
        echo '        <a class="close">×</a>' >> index.html
        echo '        <a class="play-pause"></a>' >> index.html
        echo '        <ol class="indicator"></ol>' >> index.html
        echo '      </div>' >> index.html
        echo '      <div id="links">' >> index.html
        for img in *
          do
            if [[ "$img" = *.jpg ]] || [[ "$img" = *.png ]] || [[ "$img" = *.gif ]]
              then
		base="${img%.*}"
		ext="${img##*.}"
#                while getopts ":f" opt; do
#                  case $opt in
#                    f)
                if [ "$1" = "force" ] || [[ ! -f "$thumbdir/${base}.${thumbdir}.${ext}" ]]
                  then
  		      tn=$(convert "${img}" -thumbnail "${thumbgeom}^" -gravity center -extent "${thumbgeom}" "$thumbdir/${base}.${thumbdir}.${ext}")
#                    ;;
#                  esac
#                done
                fi
                echo "        <a href=\"${img}\" data-gallery><img src=\"${thumbdir}/${base}.${thumbdir}.${ext}\" alt=\"${img}\" /></a>" >> index.html
            fi
            if [[ "$img" = *.ogv ]]
              then
                ffmpeg -loglevel panic -n -i "$img" -ss 00:00:0.635 -f image2 -vframes 1 "${thumbdir}/${img}.jpg" < /dev/null
		base="${img%.*}"
                if [ "$1" = "force" ] || [[ ! -f "$thumbdir/${base}.${thumbdir}.${ext}" ]]
                  then
		    tn=$(convert "${thumbdir}/${img}.jpg" -thumbnail "${thumbgeom}^" -gravity center -extent "${thumbgeom}" "$thumbdir/${base}.${thumbdir}.jpg")
                fi
                echo "        <a href=\"${img}\" type=\"video/ogg\" data-poster=\"${thumbdir}/${img}.jpg\" data-gallery><img src=\"$thumbdir/${base}.${thumbdir}.jpg\" alt=\"${img}\" /></a>" >> index.html
            fi
            if [[ "$img" = *.ogg ]]
              then
                echo "        <audio src=\"${img}\" controls>Your browser does not support the audio tag</audio>" >> index.html
            fi
        done
        echo '      </div>' >> index.html
    fi
}

footer () {
    echo '    </div>' >> index.html
    echo '    <footer>' >> index.html
    breadcrumbs
    echo '    </footer>' >> index.html
    echo '    </div>' >> index.html
        if [[ $depth = 0 ]]
          then  
            echo "    <script type=\"text/javascript\" src=\"//code.jquery.com/jquery-1.11.2.min.js\"></script>" >> index.html
            echo "    <script type=\"text/javascript\" src=\".js/main.js\"></script>" >> index.html
          else
            echo "    <script type=\"text/javascript\" src=\"//code.jquery.com/jquery-1.11.2.min.js\"></script>" >> index.html
            echo "    <script type=\"text/javascript\" src=\"${dots}.js/main.js\"></script>" >> index.html
        fi
    echo '  </body>' >> index.html
    echo '</html>' >> index.html
}

main $1
